name: tools_manager
description: Tools Manager

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.10
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.12
  mockito: ^5.0.17
  build_runner: ^2.1.7
  bloc_test: ^9.0.3
  fake_cloud_firestore: ^1.2.0
  firebase_auth_mocks: ^0.8.2

flutter:
  generate: true
  uses-material-design: true
